In [15]:
import os
os.chdir(r'C:\Users\sokin\Documents\Zoocamp\Homework-1')
os.getcwd()

'C:\\Users\\sokin\\Documents\\Zoocamp\\Homework-1'

In [16]:
import pandas as pd
import numpy as np

# Question 1

In [18]:
print("pandas version installed:", pd.__version__)

pandas version installed: 1.5.3


# Question 2

In [82]:
df = pd.read_csv('housing.csv')
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [27]:
print("There are",len(df.columns),"columns in the dataset")

There are  10 columns in the dataset


# Question 3

In [28]:
df.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [40]:
print('total_bedrooms has 207 missing values')

total_bedrooms has 207 missing values


# Question 4

In [43]:
 print('ocean_proximity column has', df.ocean_proximity.nunique(), 'unique values')

ocean_proximity column has 5 unique values


# Question 5

In [56]:
print('he average value of the median_house_value for the houses located near the bay is:', round(df[df.ocean_proximity=='NEAR BAY'].median_house_value.mean()))

he average value of the median_house_value for the houses located near the bay is: 259212


# Question 6
 - Calculate the average of total_bedrooms column in the dataset.
 - Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
 - Now, calculate the average of total_bedrooms again.
 - Has it changed?

###### before

In [83]:
round(df.total_bedrooms.mean(), 3)

537.871

In [84]:
null_idx = df[df.total_bedrooms.isna()].index

In [85]:
df.total_bedrooms.fillna(round(df.total_bedrooms.mean(), 3), inplace=True)

In [86]:
df.iloc[null_idx]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
290      -122.16     37.77                47.0       1256.0         537.871   
341      -122.17     37.75                38.0        992.0         537.871   
538      -122.28     37.78                29.0       5154.0         537.871   
563      -122.24     37.75                45.0        891.0         537.871   
696      -122.10     37.69                41.0        746.0         537.871   
...          ...       ...                 ...          ...             ...   
20267    -119.19     34.20                18.0       3620.0         537.871   
20268    -119.18     34.19                19.0       2393.0         537.871   
20372    -118.88     34.17                15.0       4260.0         537.871   
20460    -118.75     34.29                17.0       5512.0         537.871   
20484    -118.72     34.28                17.0       3051.0         537.871   

       population  households  median_income  median_house_value  \
290         570.0       218.0         4.3750            161900.0   
341         732.0       259.0         1.6196             85100.0   
538        3741.0      1273.0         2.5762            173400.0   
563         384.0       146.0         4.9489            247100.0   
696         387.0       161.0         3.9063            178400.0   
...           ...         ...            ...                 ...   
20267      3171.0       779.0         3.3409            220500.0   
20268      1938.0       762.0         1.6953            167400.0   
20372      1701.0       669.0         5.1033            410700.0   
20460      2734.0       814.0         6.6073            258100.0   
20484      1705.0       495.0         5.7376            218600.0   

      ocean_proximity  
290          NEAR BAY  
341          NEAR BAY  
538          NEAR BAY  
563          NEAR BAY  
696          NEAR BAY  
...               ...  
20267      NEAR OCEAN  
20268      NEAR OCEAN  
20372       <1H OCEAN  
20460       <1H OCEAN  
20484       <1H OCEAN  

[207 rows x 10 columns]

###### after

In [88]:
round(df.total_bedrooms.mean(),3)

537.871

# Question 7
 - Select all the options located on islands.
 - Select only columns housing_median_age, total_rooms, total_bedrooms.
 - Get the underlying NumPy array. Let's call it X.
 - Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
 - Compute the inverse of XTX.
 - Create an array y with values [950, 1300, 800, 1000, 1300].
 - Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
 - What's the value of the last element of w?

In [94]:
X = np.array(df[df.ocean_proximity=='ISLAND'][['housing_median_age', 'total_rooms', 'total_bedrooms']].values)

In [98]:
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [101]:
XT = X.T

In [103]:
XTX = np.dot(XT, X)

In [104]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [109]:
y = np.array([950, 1300, 800, 1000, 1300])
y.shape

(5,)

In [118]:
XTX_inv_XT = np.dot(XTX_inv, XT)
XTX_inv_XT.shape

(3, 5)

In [121]:
w = np.dot(XTX_inv_XT, y)
w

array([23.12330961, -1.48124183,  5.69922946])

In [123]:
print('last element of w:', w[-1])

last element of w: 5.699229455065586
